import os         
            #########################################################
            ############# CADERNO VIRTUAL DE RECEITAS ###############
            #########################################################

resp = ''
while resp != '0':
    os.system('cls')
    print("#########################################################")
    print("#######  CADERNO VIRTUAL DE RECEITAS CULINARIAS   #######")  
    print("#########################################################")
    print("#######           1 - Receita                     #######")
    print("#######           2 - Ingredientes                #######")
    print("#######           3 - Categoria                   #######")
    print("#######           4 - Dicas Culinárias            #######")
    print("#######           5 - Informações                 #######")
    print("#######           0 - Sair                        #######")
    print("#########################################################")
    resp = input("Escolha sua opção: ")

    if resp == "1":
        print()
        print("######################################################## ")
        print("#######             Receita                      ####### ")
        print("######################################################## ")
        print("####### 1- Nova Receita                          ####### ")
        print("####### 2- Ver Receita                           ####### ")
        print("####### 3- Editar Receita                        ####### ")
        print("####### 4- Apagar Receita                        ####### ")
        print("####### 0- Voltar                                ####### ")
        print("######################################################## ")
        resp2 = input("EScolha sua opção: ")
        if resp2 == '1':
            os.system('cls')
            print()
            print("############################################")
            print("#####           Nova Receita            ####")
            print("############################################")
            print()
            nome = input("## Nome da receita: ")
            print()
            ingredientes = input("## Ingredientes: ")
            print()
            categoria = input("## Digite a categoria da receita: ")
            print()
            tempo = input("## Digite o tempo da receita: ")
            print()
            modo_p = input("## Modo de preparo: ")
            print("#### Receita Adicionada! #### ")
            print()

        elif resp2 == '2':
            os.system('cls')
            print()
            print("############################################")
            print("#####           Ver receita             ####")
            print("############################################")
            print()
            print("## Nome: ", nome)
            print("## Ingredientes: ", ingredientes)
            print("## Categoria: ", categoria)
            print("## Tempo: ", tempo)
            print("## Modo de preparo: ", modo_p)
            print()

        elif resp2 == '3':
            os.system('cls')
            print()
            print("############################################")
            print("#####           Editar Receita          ####")
            print("############################################")
            print()
            nome = input("## Nome da receita: ")
            print()
            categoria = input("## Digite a categoria da receita: ")
            print()
            tempo = input("## Digite o tempo da receita: ")
            print()
            print("#### Receita Editada! ")
            print()

        elif resp2 == '4':
            os.system('cls')
            print()
            print("############################################")
            print("#####           Exluir Receita          ####")
            print("############################################")
            print()
            nome = input("## Nome da receita: ")
            print()
            print("Receita Excluida:", nome)
            print()
    
        print()
        input("Tecle <ENTER> para continuar...")  

    elif resp == '2':
        print()
        print("######################################################## ")
        print("#######            Ingredientes                  ####### ")
        print("######################################################## ")
        print("####### 1- Adicionar Ingrediente                 ####### ")
        print("####### 2- Ver Ingrediente                       ####### ")
        print("####### 3- Editar Ingrediente                    ####### ")
        print("####### 4- Apagar Ingrediente                    ####### ")
        print("####### 0- Voltar                                ####### ")
        print("######################################################## ")
        resp3 = input("Escolha sua resposta: ")
        if resp3 == '1':
            print()
            print("############################################")
            print("#####      Adicionando Ingrediente      ####")
            print("############################################")
            print()
            nome_i = input("## Nome do Ingrediente: ")
            print()
            marca_i = input("## Marca do ingrediente: ")
            print()
            obs_i = input("## Deixe uma observação sobre o ingrediente: ")
            print()

        elif resp3 == '2':
            print()
            print("############################################")
            print("#####         Ver Ingrediente           ####")
            print("############################################")
            print() 
            print("## Nome:", nome_i)
            print("## Marca:", marca_i)
            print("## Observação:", obs_i)
            print()
            nome_i = input("## Nome do Ingrediente: ")
            print()
            marca_i = input("## Marca do ingrediente: ")
            print()
            obs_i = input("## Observaçao do ingrediente: ")
            print()
            
        elif resp3 == '3':
            print()
            print("############################################")
            print("#####         Editar Ingrediente        ####")
            print("############################################")
            print() 
            nome_i = input("## Nome do Ingrediente: ")
            print()
            marca_i = input("## Marca do ingrediente: ")
            print()
            obs_i = input("## Observaçao do ingrediente: ")
            print()
            print("#### Ediçao feita! #### ")
            print()

        elif resp3 == '4':
            print()
            print("############################################")
            print("#####         Excluir Ingrediente       ####")
            print("############################################")
            print() 
            nome_i = input("## Digite o nome do ingrediente: ")
            print()
            print("Ingrediente Excluido!", nome_i)
            print()
        
        print()
        input("Tecle <ENTER> para continuar...")

    elif resp== '3': 
        print()
        print("########################################################")
        print("#######        Categoria de ingredientes         #######")
        print("########################################################")
        print("####### 1- Adicionar Categoria                   #######")
        print("####### 2- Ver Categoria                         #######")
        print("####### 3- Editar Categoria                      #######")
        print("####### 4- Apagar Categoria                      #######")
        print("####### 0- Voltar                                #######")
        print("########################################################")
        print()
        resp4 = input("Escolha sua opção: ")
        if resp4 == '1':
            print()
            print("############################################")
            print("#####     Adicionando Categoria         ####")
            print("############################################")
            print()
            nome_c = input("## Digite o nome da categoria: ")
            print()
        
        elif resp4 == '2': 
            print()
            print("############################################")
            print("#####           Categoria               ####")
            print("############################################")
            print()
            print("## Categoria: ", nome_c)
            print()

        elif resp4 == '3':
            print()
            print("############################################")
            print("#####       Editando  Categoria         ####")
            print("############################################")
            print()
            nome_c = input("## Digite a categoria: ")
            print()

        elif resp4 == '4':
            print()
            print("############################################")
            print("#####        Exluir  Categoria          ####")
            print("############################################")
            print()
            nome_c = input("## Digite o nome da categoria: ")
            print()
            print("Categoria Excluida!", nome_c)
            print()

        print()
        input("Tecle <ENTER> para continuar...")

    elif resp== '4':
        print("########################################################")
        print("#######            Dicas Culinárias              ####### ")
        print("######################################################## ")
        print("####### 1- Adicionar Dica Culinária              ####### ")
        print("####### 2- Ver Dicas Culinária                   ####### ")
        print("####### 3- Editar Dica Culinária                 ####### ")
        print("####### 4- Apagar Dica Culinária                 ####### ")
        print("####### 0- Voltar                                ####### ")
        print("########################################################")
        print()
        resp5 = input("Escolha sua opçao: ")
        if resp5 == '1':
            print()
            print("############################################")
            print("#####         Adicionando Dica          ####")
            print("############################################")
            print()
            nome_d = input("## Digite sua Dica: ")
            print()
            print("Você adicionou uma dica! ")
            print()

        elif resp5 == '2':
            print()
            print("############################################")
            print("#####         Dica Culinária            ####")
            print("############################################")
            print()
            print("## Sua dica culinária: ", nome_d)
            print()
        elif resp5 == '3':
            print()
            print("############################################")
            print("#####         Editando Dica             ####")
            print("############################################")
            print()
            nome_d = input("## Digite sua dica (editando): ")
            print()
        elif resp5 == '4': 
            print()
            print("############################################")
            print("#####         Excluindo  Dica           ####")
            print("############################################")
            print()
            nome_d = input("## Digite o nome da dica: ")
            print()
            print("Dica Excluida! ")

        print()
        input("Tecle <ENTER> para continuar...")

    elif resp=='5': 
        print("################################################################## ")
        print("#######                    Informações                     ####### ")
        print("################################################################## ")
        print("#######  Projeto: Caderno Virtual de Receitas culinárias   ####### ")
        print("#######  Desenvolvido por:                                 ####### ")
        print("#######  Ian Gabriel                                       ####### ")
        print("#######  UFRN - 2026                                       ####### ")
        print("################################################################## ")
        print()
        input("Tecle <ENTER> para continuar...")
    elif resp=='0':
        print()
        print("############################################")
        print("#####  Você encerrou o programa, até logo! #")
        print("############################################")
        print()
        input("Tecle <ENTER> para continuar...")
    else:
        print()
        print("############################################")
        print("#####   Você digitou uma opção inválida ####")
        print("############################################")
        print("#####                                   ####")
        print("#####      Retorne ao menu anterior     ####")
        print("#####         e tente novamente         ####")
        print("#####                                   ####")
        print("############################################")
        print()
        input("Tecle <ENTER> para continuar...")

print("Fim")


